dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "backpex",
    "confm",
    "customisable",
    "daum",
    "dmi",
    "dotenv",
    "erd",
    "figma",
    "gangnam",
    "geocoder",
    "geocoding",
    "gwp",
    "htt",
    "iex",
    "ipcc",
    "juso",
    "kakao",
    "kubectl",
    "liveview",
    "llm",
    "lookups",
    "lsof",
    "mce",
    "mcf",
    "mcp",
    "naymspce",
    "otp",
    "poc",
    "prd",
    "saa",
    "testjusogokr",
    "tidewave",
    "ui's",
    "uno",
    "volatilisation",
    "wishket",
    "yymmddhhmm",
]
ignore_paths = ["package.json"]
ignore_patterns = [
    "[가-힣]+",
    "[a-zA-Z0-9]+[가-힣]+",
    "[가-힣]+[a-zA-Z0-9]+",
    "[a-zA-Z0-9가-힣]+[가-힣]+",
    '\w{17,}',
]
